### PR TITLE
Fix tsung config

### LINKED ISSUE #74: Fix tsung config
After the api changed the tsung config is not working anymore, this due to the socket api payload was changed.

### PR DESCRIPTION
**Pull request by Hanspagh**
Simplified both the local and prod tsung config, so its only sending one kind of player. I tried to make it possible to add more players by adding them in a file. This was to avoid a lot of code duplication and make it a little bit easier to grasp the player objects, but had no luck, due to tsung missing some features to make it possible :(

Also updated the validate player json to throw a bit more sensible errors 
Closes #74

### CODE REVIEW

**Comment by ecly** [comment]
@Hanspagh hmm - when I run it by doing`iex -S mix phx.server` in one terminal and running tsung with `tsung -f tsung-config.local.xml start` in another, I seem to be getting a lot of exceptions raised from an argument error in player.ex:125 from calling:
` :erlang.binary_to_existing_atom("jungle", :utf8)`

Honestly, that call should be fine, seeing as we definitely already have the `:jungle` atom available. I assume you're not running into the same issue. Otherwise it definitely looks nice! Will be nice to get some shorter tsung-configs.

File: apps/buddy_matching/lib/players/player.ex [hunk 1]
```diff
@@ -75,13 +77,29 @@ defmodule BuddyMatching.Players.Player do
   https://support.riotgames.com/hc/en-us/articles/201752814-Summoner-Name-FAQ
   """
   def validate_player_json(data) do
```
Comment (ecly) [inline apps/buddy_matching/lib/players/player.ex]: This is definitely awesome - suppose eventually we can do the same for the criteria validation. And if any nitpickery is to be done, I'd go with "Bad criteria" instead of "Wrong criteria".

**Comment by ecly** [comment]
@Hanspagh - oh so it works if you manually type out the different roles as atoms prior to running it? 
Definitely weirds as we are certainly using all role atoms in non-test code already, so they should very much be registered as existing, prior to the requests from tsung.

**Comment by Hanspagh** [comment]
@ecly Changed bad criteria text, not sure what to do about the missing atoms

**Comment by ecly** [comment]
@Hanspagh alright - I think I know why it happens. In prod, the place at which the role atoms are first introduced is at RiotApi.role_from_match/1. In prod, we'll always have at least a single call to the Riot API before any player needs to be parsed from JSON. 
There is a bit of discussion about this behavior of String.to_existing_atom/1 at:
https://github.com/elixir-lang/elixir/issues/3654.

By manually calling RiotApi.role_from_match/1 from IEx, no matter the input, the error will no longer occur when running tsung afterwards. We can fix it by simply adding a single call to RiotApi before the rest of the config runs.

**Comment by Hanspagh** [comment]
@ecly Found quite a nice solutions , to ensure the atoms are loaded, suggested by Jose him self.

**Comment by ecly** [comment]
@Hanspagh yummy - looks nice!
